src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Image = null;


    #[ORM\ManyToOne(inversedBy: 'article')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'articles', targetEntity: Comments::class, orphanRemoval: true)]
    private Collection $Comments;


    public function __construct()
    {
        $this->Comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }



    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->Comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->Comments->contains($comment)) {
            $this->Comments->add($comment);
            $comment->setArticles($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->Comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticles() === $this) {
                $comment->setArticles(null);
            }
        }

        return $this;
    }


}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\Comments;
use App\Form\ArticleType;
use App\Form\CommentType;
use DateTime;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    #[Route('/', name:'home')]
function home(): Response
    {
    return $this->redirectToRoute('articles');
    // return $this->render('blog/home.html.twig');
}

#[Route('/articles', name:'articles')]
function articles(ManagerRegistry $doctrine, Request $request): Response
    {
    dump($this->getUser());
    $pages = $request->get('page', 1);
    $entityManager = $doctrine->getManager();
    $articles = $entityManager->getRepository(Articles::class)
        ->findBy(array(), array(
            'createdAt' => 'DESC',
        ), 5, ($pages - 1) * 5);
    $articlesNumber = count($entityManager->getRepository(Articles::class)->findAll());
    $numberPages = ceil($articlesNumber / 5);
    // dd($articles[0]->getUsers()->getLogin());

    return $this->render('blog/articles.html.twig', [
        'articles' => $articles,
        'nbPages' => (int) $numberPages,
    ]);
}

#[Route('/article/{id}', name:'article')]
function article(ManagerRegistry $doctrine, $id, Request $request): Response
    {
    $entityManager = $doctrine->getManager();
    $article = $entityManager->getRepository(Articles::class)->find($id);
    $comment = new Comments();
    $comment->setUser($this->getUser());
    $comment->setArticles($article);
    $form = $this->createForm(CommentType::class, $comment);
    $form->handleRequest($request);
    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->persist($comment);
        $entityManager->flush();
    }

    return $this->render('blog/article.html.twig', [
        'article' => $article,
        'commentTypeForm' => $form->createView(),
    ]);

}
#[Route('/newarticle', name:'article_form')]
function newArticle(ManagerRegistry $doctrine, Request $request): Response
    {
        $article = new Articles();
        $article->setCreatedAt(\DateTimeImmutable::createFromMutable(new DateTime()))
        ->setUser($this->getUser());
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('Image')->getData();
            if ($imageFile){
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = "/".$this->getParameter('image_path').$safeFilename.'-'.uniqid().'.'.$imageFile->guessExtension();
                $imageFile->move(
                    $this->getParameter('image_path'),
                    $newFilename
                );
                $article->setImage($newFilename);
            }
            $entityManager = $doctrine->getManager();
            $entityManager->persist($article);
            $entityManager->flush();
            return $this->redirectToRoute('articles');
        }
        
    return $this->render('blog/articleForm.html.twig', [
        'test' => 'test',
        'artcleFormType' => $form->createView() 
    ]);
}
}

templates/blog/article.html.twig
{% extends "base.html.twig" %}
{% block title %}Acceuil
{% endblock %}
{% block body %}
	{# {{dump()}} #}
	<div>
		<h1>{{article.title}}</h1>
		<img src="{{ article.image }}" class="card-img" alt="...">
		<p>{{article.description}}</p>
		<p>De :
			{% set usernameA = article.getUser.getEmail|split("@")   %}

			{{usernameA[0]}}</p>
		<p>Le :
			{{article.getCreatedAt|date('d/m/Y')}}</p>
		<h2>Commentaires</h2>
		{% for comment in article.getComments  %}
			<div>
				{% set usernameC = comment.getUser.getEmail|split("@")   %}
				<h3>Par
					{{ usernameC[0] }}</h3>
				<fieldset>
					<legend>
						<h4>{{ comment.getTitle }}</h4>
					</legend>
					<span>{{ comment.getDescription}}</span>
				</fieldset>
			</div>
		{% endfor %}
		<div>
			<p>
				<a href={{ path('articles')}}>Retour à la liste des articles</a>
			</p>
		</div>
		{% if app.user %}
			<h4>Ecrire un commentaore</h4>
			{{form(commentTypeForm)}}
				{% else %}
					<h4>Veuillez vous connecter</h4>
			{% endif %}
		{% endblock %}

templates/blog/articleForm.html.twig
{% extends "base.html.twig" %}
{% block title %}Créer votre articles
{% endblock %}
{% block body %}
{{form(artcleFormType)}}
{% endblock %}

templates/blog/articles.html.twig
{% extends "base.html.twig" %}
{% block title %}Acceuil
{% endblock %}
{% block body %}
	{% for article in articles %}
		<div class="article">
			<h1>{{ article.title }}</h1>
			<img width="640" height="480" src="{{ article.image }}"  class="card-img" alt="...">
			<p>{{ article.description }}</p>
			{% set usernameA = article.getUser.getEmail|split("@")   %}
			<p>De :
				{{usernameA[0]}}</p>
			<p>Le :
				{{ article.getCreatedAt|date('d/m/Y') }}</p>
			<p>
				Il y'a
				{{ article.getComments|length}}
				{{article.getComments|length > 1 ? "commentaires" : "commentaire" }}</p>
			<p>
				<a href="{{ path('article', {'id': article.id}) }}">Voir l'article</a>
			</p>
		</div>
	{% endfor %}
	<div>
		{% for i in range(0,nbPages - 1) %}
			<span>
				<a href={{ path('articles') }}?page={{i + 1}}>{{i + 1}}</a>
			</span>
		{% endfor %}
	</div>
{% endblock %}

templates/blog/home.html.twig
{% extends "base.html.twig" %}
{% block title %}Acceuil{% endblock %}
{% block body %}
    Mon Super Blog
{% endblock %}